### ISSUE TITLE
Inspector can't find/navigate "tagged" files in Finder.app

### ISSUE THREAD

**Issue by johnaaron-git** [godbout/Wooshy.docs#105]
Wooshy is unable to navigate the "Tags" tabs of Finder.app **during file selection** (the finder pop-up window); it looks like the inspector can't detect them. Folders/files outside of "Tags" work normally.

I've attached a video of the behavior below:

https://user-images.githubusercontent.com/32317888/210374050-287f6f81-ebc1-4daf-bb1d-e35bde1ce79a.mp4

**Comment by godbout** [comment]
a few questions:
1. can you switch from a `column` view to another view, like list, and see if this happens again?
2. does it only happen with tags? can you try any other place where your folder view options is set to `column`?

i'm having the same problem with the `Download` folder. my view options are `column`, and the content is not reachable by Wooshy. it's not reachable by Homerow, Vimac and Shortcat either. the reason is that for whatever reason that part is disconnected from the Finder tree. as all of those apps—including Wooshy—have to go through the AX tree of the frontmost app, if Apple doesn't give us the data, we can't get it. 

but maybe i'm wrong in your case, who knows. answering the two questions above will help me narrow down and investigate further. thanks.

**Comment by johnaaron-git** [comment]
Interesting, list/icon view works fine for "Tags" categories during file selection:

<img width="931" alt="Screenshot 2023-01-03 at 4 57 15 PM" src="https://user-images.githubusercontent.com/32317888/210393701-2aa440b5-1635-4f61-a6ac-eff5500822e9.png">

Non-"tagged" files/folders in column view seem to work too:
<img width="978" alt="Screenshot 2023-01-03 at 5 01 34 PM (2)" src="https://user-images.githubusercontent.com/32317888/210394729-3bd7144a-31e2-45bb-b483-81d37cd72ee6.png">

**Comment by johnaaron-git** [comment]
Wooshy still works even with the weird "Media" locations, like "Music" and "Movies":
<img width="982" alt="Screenshot 2023-01-03 at 5 17 29 PM (2)" src="https://user-images.githubusercontent.com/32317888/210397288-b3517d31-6427-4a4e-a66a-02c8e1abe46a.png">

It doesn't work with the "Photos" custom view though, but tbh "Media" locations break normal Finder features anyways (like view or grouping options)

**Comment by johnaaron-git** [comment]
Sorry, to answer your questions directly:

1.) Wooshy works fine navigating "Tags" in the Finder selection pop-up window when "Icons" or "List" views are selected
2.) The issue only appears for "Tags" (in default column view) and "Media -> Photos" in the Finder selection pop-up window. Other folders in column view seem to work fine.

**Comment by godbout** [comment]
my investigation until now (not from today, it's been a while because i'm struggling with the same issue for myself) is that it fails in `column view` everywhere there is a "bar title" on top of the column. it fails basically for every folder, whether it's `download`, `tags`, `music`, etc.

gonna drop a video below to show. i'm pretty sure it's the same issue you're encountering. if you can play around like in the video and confirm that's be nice. the big problem is, as far as i'm concerned, i can't do anything about it because i don't have access to the UI Elements. the fact that Shortcat and Vimac/Homerow are having the same issues tell me i'm not that crazy. i think the only thing i can do on my side for now is create another FB for Apple to fix their shit 😅️

**Comment by godbout** [comment]
https://user-images.githubusercontent.com/121373/210692034-de637ed5-4f40-4a8a-bda4-7207139663e1.mp4

**Comment by godbout** [comment]
so as you can see from the video above, it's as soon as there's a `column title` that Wooshy fails because the UI Elements are not reachable. if i had to guess i'd say that some people at Apple decided to make Finder prettier/a little more useful but didn't care about the Accessibility support.

**Comment by johnaaron-git** [comment]
Ah, yeah I can reproduce exactly what you're seeing. Wooshy works everywhere now, as long as "group items by:" is set to "None".

I appreciate your insight, thank you!

**Comment by godbout** [comment]
> Ah, yeah I can reproduce exactly what you're seeing. Wooshy works everywhere now, as long as "group items by:" is set to "None".

yep. i know, not ideal, but nothing else we can do until Apple fixes. i'll post the link to the FB once i send it.

> 
> I appreciate your insight, thank you!

you're welcome! i know Wooshy (and kV) is a bit more wonky than what we would like it to be, but that's unfortunately the result of dealing with external apps, rather than having a self-contained app. but we'll try to keep smoothing things out as much as possible.

**Comment by godbout** [comment]
reported to Apple: https://github.com/feedback-assistant/reports/issues/375
