### ISSUE TITLE
Gmail Compose Window seems transparent

### ISSUE THREAD

**Issue by hasantahir** [godbout/Wooshy.docs#110]
The Compose pop-up window is kind of transparent to Wooshy. The compose window is an overlay window and the inspector identifies contents hidden behind the mail.

https://user-images.githubusercontent.com/11236148/215086386-7ccd3b74-3c03-40f4-82a1-04f802ab00f6.mov

https://user-images.githubusercontent.com/11236148/215086337-cba97a3a-d417-4f40-a6a4-5545f56878f2.mov

**Comment by godbout** [comment]
can't you access anything you need? 

currently, my two thoughts:
1. The Inspector grabs the smallest UI Element that is under the mouse cursor. the macOS AX doesn't care about z-index, so you can't know what's on top and what's below. the best way i found to cope with this and show as many UI Elements as possible is to grab the smallest of what's under the cursor. which is why you see what you see.
2. AX info should be provided with HTML elements, so i guess the whole compose window is still reachable? not sure what option you use to get Gmail showing up that way. i don't use the Gmail web interface, but if i'm trying currently it looks like this:

https://user-images.githubusercontent.com/121373/215095044-5b51d40e-82bd-46cc-9aa1-f6af1e1db331.mp4

as you can see, stuff are reachable. but yeah, The Inspector catches stuff under. as far as i know there's no way to avoid this as, again, there's no z-index data. if i grab the biggest UI Elements, you'll miss all the UI Elements that are _within_ other UI ELements. if i grab the smallest UI Elements, you'll get more Elements, but sometimes you'll have the experience that you're showing in your videos.

**Comment by godbout** [comment]
(seems for whatever reason the mouse is not shown in my video. makes it a bit harder to understand what The Inspector is showing. sorry about that!)

**Comment by godbout** [comment]
also, something else. when you're dealing with macOS apps, windows are real windows. so Wooshy can focus on the frontmost window, and ignore the other ones. all the web and Electron shits, windows are fake windows 😅️ there's just pretending through UI tricks, but in reality the whole structure behind is crap. so Wooshy will not be able to distinguish.

as i know you've been using Shortcat and Homerow, how are those guys handling there?

**Comment by hasantahir** [comment]
This was recorded inside Chrome :-). Shortcat is showing the same:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/11236148/215107681-38687b5d-8ea9-4679-8248-bc6cb951618b.png">
 
Haven't used Homerow but looks like it will also behave similarly inside Chrome. Thanks again for looking into this.

**Comment by godbout** [comment]
got the latest Chrome, the composer window looked small still for me. checked the Settings but found nothing. actually it's just that i had to put it in fullscreen.

checked and yeah, Homerow is doing the same, as you can see from the video below. makes sense, as we don't have z-index data from the AX, so our best guess is to grab the smallest UI Element, so that we grab nested ones.

https://user-images.githubusercontent.com/121373/215236959-74ff0552-581b-4318-ae97-95e6cec30cfd.mp4
