### ISSUE TITLE
Feature Request: click selector similar to vimium `f` key.

### ISSUE THREAD

**Issue by roryfahy** [godbout/Wooshy.docs#115]
I know there are other apps out there trying to do this but they're way too slow. 
I know you're going for a minimal look but this hits a couple use-cases that causes me to use my mouse.  (maybe it could be an alternate config setting?)

Wooshy has become one of the most indispensable pieces of software that I now rely on every day. (alfred, vimium, etc..)
The problem is sometimes I press `*` to see that there is a possibility of highlighting a particular link, however I dont know what the letters are for that given link so i'm not aware of a solution other than to use my mouse to hover and find out what it the selection text should be (once I have it memorized it stops being a problem, but I have a shit memory so...).  the other thing is sometimes a UI element is so generic and doesn't expose enough unique text to distinguish it from 14 other selections which leads to excessive tabbing. 

Do you know of a existing way to solve these issues? if not would this be a possibility on your roadmap?

vimium `f` key example
<img width="746" alt="image" src="https://user-images.githubusercontent.com/42627486/218468910-f9978088-145d-4b64-b650-cacd1b30fc86.png">

**Comment by godbout** [comment]
> however I dont know what the letters are for that given link so i'm not aware of a solution other than to use my mouse to hover and find out what it the selection text should be

i've had the idea of adding the possibility to bring The Inspector somehow without hovering. but because i never really had the strong need myself, and nobody has been asking, i've haven't dug deeper for now.

> (once I have it memorized it stops being a problem, but I have a shit memory so...)

yeah that was the idea with The Inspector and the mouse hovering. usually once you've got your UI Element once, it'll stick. for some people 😅️ also maybe i'm just personally using only the same apps and webpages. that's possible.

> the other thing is sometimes a UI element is so generic and doesn't expose enough unique text to distinguish it from 14 other selections which leads to excessive tabbing.

yes, i understand this issue. personally i combine Wooshy with kindaVim, so i quickly go through the extra Targets with Vim moves. doesn't happen often tho.

> Do you know of a existing way to solve these issues? if not would this be a possibility on your roadmap?

so. finally, the bad news. no, i have no plan at all to add hints. i personally don't like them, and find that they cause more brain friction for me. that's why i created Wooshy in the first place, as a replacement to Vimac (also Vimac was pretty slow). the adult thing for me to do now: introduce a competitor. you may want to have a look at [Homerow](https://homerow.app). Homerow started as the new Vimac, with the hints. then a few months ago it switched to à la Wooshy, with the search. now it combines both. so, in your case, you could get the best of the both worlds: the search to start with, and the hints only if needed.

in the case of Wooshy, there's a roadmap, but it doesn't include hints, deliberately. sorry!

**Comment by godbout** [comment]
closing as this will not be done. Homerow and Shortcat do this.
