### ISSUE TITLE
support for ipad?

### ISSUE THREAD

**Issue by roryfahy** [godbout/Wooshy.docs#119]
is there any possibility that you’d consider making this app support ipados?  I realize this is a super non trivial ask and potentially not even possible, not sure.  It would be very useful I know theres an ipad community that is currently pretty frustrated with the limited power user tooling so could be a good market.

**Comment by godbout** [comment]
so, two things:
1. the [Accessibility APIs](https://developer.apple.com/documentation/applicationservices/axuielement) needed to grab all the info necessary for Wooshy to do its magic is **only available for macOS** (started with Jaguar, 19 years ago. those are very old APIs).
2. not 100% sure, but i think there's no APIs on iOS/iPadOS to do what Wooshy does with macOS
3. i personally mostly use Macs, so i'm not gonna dig into iPadOS. business-wise the trio kindaVim/Wooshy/Scrolla is a very bad decision. but i keep going because i mostly built those apps for myself. would make no sense for me to go into a iPadOS version, sorry.

**Comment by godbout** [comment]
not gonna be done. closing. please reopen if there's more to discuss.
