### ISSUE TITLE
does not work with Things 3

### ISSUE THREAD

**Issue by aaronrolls** [godbout/Wooshy.docs#12]
To be fair, Homerow and shortcat do not work with Things 3 ether. Homerow can click about 25% of what it needs to. Shortcat about 5%.

It could likely be an issue with Things 3 but I don't know how to test that.

**Comment by godbout** [comment]
that's another interesting one. i use Things 3 heavily, and yeah, not working great. basically most of the app is custom UI and they didn't set Accessibility attributes:

https://user-images.githubusercontent.com/121373/180909181-b10e1d62-5e2d-4811-8619-9c429cea8546.mp4

now Homerow does give hint, but the clicks actually don't work. BUT. the new Shortcat works on the inner checklists. that is really cool. so there's something possible here too for Wooshy:

https://user-images.githubusercontent.com/121373/180909511-8fbd5ef4-996d-4364-bb1b-58e3aecead66.mp4

i'll ask the guys from Things to add the Accessibility data. thanks for pushing! 💪🏼️

**Comment by roelvangils** [comment]
Things is one of the (very rare) apps that will not benefit so much from Wooshy because of its excellent Quick Search feature. You don't even have to `⌘F`, but just start typing to make it appear. It took a while for me to get used to that behaviour, but now it feels completely natural. I think that using Woohsy for (almost) everything else, will soon feel like second nature as well! Looking forward tot the next update!

**Comment by roelvangils** [comment]
This one, I mean:

![20220726_135822_Things@2x](https://user-images.githubusercontent.com/103744/181001208-0fcb5425-f30f-4a6c-b2c6-4c4ef2bd8638.png)

**Comment by godbout** [comment]
> Things is one of the (very rare) apps that will not benefit so much from Wooshy because of its excellent Quick Search feature. You don't even have to `⌘F`, but just start typing to make it appear. It took a while for me to get used to that behaviour, but now it feels completely natural.

that is actually true. i use it also all the time. but i find myself starting Wooshy too out of habit. and it'd be nice if we could target stuff in Things. i'll ping the dev and will update on this thread.


> Looking forward tot the next update!

of Wooshy? 😟️ that was it. as far as i'm concerned it's finished.

**Comment by godbout** [comment]
> This one, I mean:
> 
> ![20220726_135822_Things@2x](https://user-images.githubusercontent.com/103744/181001208-0fcb5425-f30f-4a6c-b2c6-4c4ef2bd8638.png)

can't see. do you have a bigger version? 🤔️

(sorry. 😗️)

**Comment by roelvangils** [comment]
> can't see. do you have a bigger version? 🤔️

Well, if you insist :)

[bigger.jpg.zip](https://github.com/godbout/Wooshy.docs/files/9190912/bigger.jpg.zip)

**Comment by godbout** [comment]
is that 720 or 1080p? actually i don't take anything under 4k.

**Comment by roelvangils** [comment]
I cheated. It's a Retina screenshot upscaled with [Pixelmator Pro](https://www.pixelmator.com/blog/2019/12/17/all-about-the-new-ml-super-resolution-feature-in-pixelmator-pro/).

**Comment by godbout** [comment]
![200w](https://user-images.githubusercontent.com/121373/181042789-72c2e1e5-6671-4079-81ba-499baa58177b.gif)

**Comment by godbout** [comment]
ping the devs asking them to add AX info. thoughts and prayers now.

**Comment by roelvangils** [comment]
Maybe [this helps](https://twitter.com/roelvangils/status/1552688861754556416).

**Comment by godbout** [comment]
thanks. actually they answered me by email like an hour ago. they said 1) yes it could be improved 2) they want to improve 3) they have no timeline.

i'll shoot a video tomorrow and will send them.

**Comment by roelvangils** [comment]
The development of Things is reaaaaallllly slow. The app is updated regularly, but they seldom release new features. I hope they are secretly working on Things 4.

**Comment by godbout** [comment]
> The development of Things is reaaaaallllly slow. The app is updated regularly, but they seldom release new features. I hope they are secretly working on Things 4.

i use Things 3 every day. all my day to day tasks are there. but tbh i frustrates me, like 1Password 7 frustrated me (not even talking about 8 please). there's bugs that have been there for years. reported many times. and still, you need to quit the app a few times a day coz it's not clickable, etc. fh.

**Comment by godbout** [comment]
ok so i've spent quite some time on this, trying to get AX data from Things, and i can't. not sure why. it's on me. some part of the app just has no data, but some part has, and it's weirdly not straightforward to access it. even with the Accessibility Inspector:

https://user-images.githubusercontent.com/121373/181609020-23bee706-90e6-4f69-9bc5-1423e8e3293b.mp4

the issue Wooshy has is that it gets the checklist data, but the AX returns the size and position of the parent. exactly like what the Accessibility Inspectors does, until you do the trick to go check and click the children and THEN only you have access to them, with the correct size/position. seems there's a trick to do, also programmatically, and i don't know what it is yet. this will take more time to solve, because it's basically my AX engine, and my knowledge, that are missing something. but ultimately the checklist should be searchable by text. @aaronrolls maybe you have some ideas? you said you're below average but i saw you're like the master of Accessibility Inspector. also are you looking for a job?

**Comment by godbout** [comment]
well, kinda good news:

https://user-images.githubusercontent.com/121373/181617809-04241445-a3d0-4ae6-841d-107b39dc7efa.mp4

but it's gonna break some other stuff. so is working with the AX APIs.

**Comment by aaronrolls** [comment]
I see what you mean, Things 3 has almost no info, expect for when you've opened a task and it isn't great then. It could be done with OCR if you end up doing that.

It could also be done with something like Homerow, providing that the app acted differently in things 3 than elsewhere. But since the idea behind Wooshy is to type the name of what you want, I can't find a way. Without OCR I don't think anything you could patch together would be easier than the in built shortcuts.

All they need to do is add the title of the Todo/Project to the cell `Label` and it would be easy. But I don't have much hope of them doing that.

I asked them to fix a bug for me about a week ago, they got back to me in a couple of days saying that it had been fixed in the latest version. It hadn't. They couldn't give me a timeline once I let them know.

**Comment by godbout** [comment]
> I see what you mean, Things 3 has almost no info, expect for when you've opened a task and it isn't great then. It could be done with OCR if you end up doing that.

OCR is "in the roadmap" with currently a 2% chance of it happening coz 1) it's another complete universe 2) as far as my first tests go it's slow. that would tho bring Wooshy in images and stuff like that. but at the same time i'm not sure it's worth the work. if you start dealing with images etc maybe the mouse is indeed better? rather than `right click` through Wooshy etc.

> It could also be done with something like Homerow, providing that the app acted differently in things 3 than elsewhere. But since the idea behind Wooshy is to type the name of what you want, I can't find a way. Without OCR I don't think anything you could patch together would be easier than the in built shortcuts.

you mean Ws showing hints if it can't find text? i guess there's stuff to do, like if you have a bunch of rows or cells next to each other with absolutely no info, we could make Ws reach them through typing 1/2/3 etc. but maybe that would clash with other things? i don't know. tbh yeah, not something i'm thinking about spending time on, at least not now, not as long as it isn't becoming a big friction. in the case of Things 3, actually using the built-in search for the tasks, and Ws for the checklists works pretty well. not "ideal", you need to build a bit of a habit, but ultimately you can reach what you want fast. i've been using kV and the `fn jk` to go up and down checklists. Ws feels already like a way better solution (a6, my version :p)

> All they need to do is add the title of the Todo/Project to the cell Label and it would be easy. But I don't have much hope of them doing that.

> I asked them to fix a bug for me about a week ago, they got back to me in a couple of days saying that it had been fixed in the latest version. It hadn't. They couldn't give me a timeline once I let them know.

yeah i've asked them to fix stuff like years ago, still nothing. reminds me of dealing with the 1Password team. like sometimes you can't click and select checklists at all. need to restart the app. been years. nothing done. but currently when people report issues with apps while using kV/Ws, i report to the developers. Things 3 is no exception. they're gonna receive a big fat video soon. also i'm becoming famous and now those guys answer my tweets hahahhahaha so 🤞️

**Comment by godbout** [comment]
anyways regarding Things 3, getting the checklists will be fixed. and that's great, coz that means overall improvement of the Ws' AX engine. thanks for the report!

**Comment by godbout** [comment]
(big fat video dropped.)

**Comment by godbout** [comment]
ok, after a nice lunch, fixed. whole AX Engine improved. same speed. will just find more, proper targets. (no pollution added.)

**Comment by godbout** [comment]
support improved in a6: https://github.com/godbout/Wooshy.docs/releases/tag/1a.6

i don't think we can do much more now. gonna be up to the Things devs.

**Comment by godbout** [comment]
i wanna close this one. nothing much we can do until the guys at Culture Code do something. any objection?

**Comment by godbout** [comment]
@roelvangils i actually use it a lot coz for the checklists when i'm within a task. i find it super useful.

https://user-images.githubusercontent.com/121373/182978912-607cfc1f-958f-4e35-bb51-adeb44d0ce6b.mp4

**Comment by godbout** [comment]
nothing to do here anymore. closing.
