### ISSUE TITLE
Not working with breadcrumbs in Webstorm (Idea IDEs)

### ISSUE THREAD

**Issue by Josh-Piper** [godbout/Wooshy.docs#123]
Hey! I'm [following on from the kindaVim issue](https://github.com/godbout/kindaVim.docs/issues/181) that was actually related to Wooshy.

On Webstorm I have all the panels hidden apart from the breadcrumbs and tabs. When I am within a function/class I want to be able to navigate up to its declaration's similar to Neovim's/Visual Studio Code's features sticky headers/scroll.

When I activate Wooshy, the breadcrumbs do not register as being clickable and so does not show up.

![Bright-Sunny-Day-Say-Hip-Hip-Hooray-2023-06-17 at 11 27 19@2x](https://github.com/godbout/Wooshy.docs/assets/35862340/d0030a24-1d37-4d8c-b26f-f7a7a0ec98f3)

For context, I have tried this using the alternative's listed in the Wooshy docs and Homerow, Shortcat, Vimac do not work, but Superkey can find it. So unsure if this isn't accessible or not since Superkey looks to be using ocr.

**Comment by godbout** [comment]
> For context, I have tried this using the alternative's listed in the Wooshy docs and Homerow, Shortcat, Vimac do not work, but Superkey can find it. So unsure if this isn't accessible or not since Superkey looks to be using ocr.

so yeah, two things here. usually if Wooshy can't grab something, and Vimac/Shortcat/Homerow can't either, that means that those UI Elements are not part of the Accessibility tree. those apps use the Accessibility features to go through the list of UI Elements, but we can't do magic when the Elements are not there 😂️

you're right regarding Superkey. it's using OCR. it's a bit slower, but it'll grad other sorts of stuff. like Superkey is definitely more useful in PDFs for example, where it grabs text while Wooshy etc. only see one big UI Element. 

> When I activate Wooshy, the breadcrumbs do not register as being clickable and so does not show up.

saying this, tho, i can grab the breadcrumbs here. am i testing this wrongly?

https://github.com/godbout/Wooshy.docs/assets/121373/a5cccb10-187e-43fe-beb5-916e60ef0588

but you may notice a few things:
1. Wooshy seems slow to catch up. not sure if because the AX tree is huge, or i'm on Sonoma (buggy). there's some stuff i wanna improve in Wooshy regarding the speed, but maybe it's also a OS beta preview thing
2. once you click on a breadcrumb, WebStorm seems to launch a whole new window, that looks like a menu. so when you run Wooshy on that new window/menu, you'll see that only the items of that menu are targeted. probably there's nothing i can do here. it's how WebStorm is built. but not sure yet if this is a JetBrains Toolbox thing or not. will have to investigate more.

**Comment by Josh-Piper** [comment]
![Bright-Sunny-Day-Say-Hip-Hip-Hooray-2023-06-17 at 18 59 25@2x](https://github.com/godbout/Wooshy.docs/assets/35862340/43b0a466-7197-42a7-a734-54148bc1d866)

I've attached what the breadcrumbs are. From your video it seems Wooshy can't identify them either...

You are right about the status bar working (which you are clicking through). I can use that as an alternative, I just originally had that hidden since it contains a lot of unnecessary information about git etc. that I didn't want shown.

Let me know your thoughts!

**Comment by godbout** [comment]
> ![Bright-Sunny-Day-Say-Hip-Hip-Hooray-2023-06-17 at 18 59 25@2x](https://user-images.githubusercontent.com/35862340/246598154-43b0a466-7197-42a7-a734-54148bc1d866.png)
> 
> I've attached what the breadcrumbs are. From your video it seems Wooshy can't identify them either...
> 
> You are right about the status bar working (which you are clicking through). I can use that as an alternative, I just originally had that hidden since it contains a lot of unnecessary information about git etc. that I didn't want shown.
> 
> Let me know your thoughts!

alright, got it. thanks.

yet, not available. not even Apple's own Accessibility Inspector can get them. probably custom UI. without AX support. only thing to do here is to report to JetBrains. usually i contact devs when it's the whole app that is not working. but for just the breadcrumbs i'm gonna pass sorry 😂️😂️😂️

https://github.com/godbout/Wooshy.docs/assets/121373/7cf8c19e-09b9-4ed2-895d-9d8f32951ec0

**Comment by Josh-Piper** [comment]
Wow! I don't know if that's a good thing or bad thing that JetBrains has a custom UI there haha. Feel free to close this, I reckon I can get by using the status bar instead for now. Might give me a reason to swap over to Neovim in the future haha

**Comment by godbout** [comment]
> Wow! I don't know if that's a good thing or bad thing that JetBrains has a custom UI there haha. Feel free to close this, I reckon I can get by using the status bar instead for now. Might give me a reason to swap over to Neovim in the future haha

yeah that's always the problem with apps that are supposed to be "multiplatform" you can kinda use them on each platform, but they're not that adapted. personally i avoid as much as i can.

if you don't need a full IDE, and want something native, maybe you can have a look at [CotEditor](https://github.com/coteditor/CotEditor) too. native. so it works beautifully with kindaVim, Wooshy and Scrolla. i guess Neovim would be Terminal only.
