### ISSUE TITLE
How is Wooshy so much faster than other apps like Shortcat and Homerow?

### ISSUE THREAD

**Issue by YousufSSyed** [godbout/Wooshy.docs#126]

**Comment by godbout** [comment]
but is it tho? 🤔️

i built Wooshy because i liked the idea of [Vimac](https://github.com/dexterleng/vimac) but 1) it was too slow 2) i didn't like hints, i wanted to type where i wanted to go. hints for me require some sort of deciphering and thinking and it breaks my flow. typing is more natural.

i saw at the time from Vimac's code that it was using some library that was not really done for that, hence the slowness. so i built Wooshy. i had quite the experience with the macOS Accessibility framework as i had spent two years full-time building [kV](https://github.com/godbout/kindaVim.docs). so i knew where to go.

basically to make sure i understand what i'm doing and to get the max performance, i built from scratch. i do my own libraries that fit exactly my needs. nothing extra. that requires a lot of time, research, etc. but i love this. every morning at coffee ☕️ i've got about 15 libraries for the 3 apps i'm building (kV, Wooshy, Scrolla). so i think this plays a role.

also i'm focused about the UX. don't care much about time or money. as far as i'm concerned i'm building art (i did paintings, music, writings. software is just one part of my life that i approach in a same way).

that being said, that's just my own way. if i'm not wrong the newest Homerow (the one that now also has the typing) is fast. i haven't used Shortcat in a while (a bit too messy for me) but i think it's fast too? also i believe they should be faster with web pages. they're using specific stuff to query elements which i don't use (yet).

**Comment by YousufSSyed** [comment]
Did you look at Vimac's code for Wooshy? And what API do you use to actually click the buttons with the app?

**Comment by godbout** [comment]
> Did you look at Vimac's code for Wooshy?

no. i had built my own knowledge of the Accessibility Framework through developing [kV](https://github.com/godbout/kindaVim.docs) for two years first. but i was curious to see why Vimac was slow.

> And what API do you use to actually click the buttons with the app?

trying to build your own app? 😂️
as usual with that part of macOS, it's tricky. you start developing something and you find it doesn't work in other apps, etc. everything comes from the Accessibility Framework: https://developer.apple.com/documentation/applicationservices
but to generate clicks for example, you maybe have different ways depending on whether it's a button, a radio-button, etc., the side effects you want (or don't want) blah blah blah.
