### ISSUE TITLE
does not activate when the curser is in the password field

### ISSUE THREAD

**Issue by aaronrolls** [godbout/Wooshy.docs#13]
I'm not sure if this is by design but it does activate when the macos autofill drop down menu is showing but the curser is in the username field.

**Comment by aaronrolls** [comment]
Scratch that, it looks like it does not activate when the curser is in the password field and it has nothing to do with the macos autofill

**Comment by godbout** [comment]
by design macOS doesn't send key presses to event wiretaps when in Secure Input fields: https://smile.helpscoutdocs.com/article/402-textexpander-and-secure-input

that being said, you can activate Alfred. so there's definitely a way. but i'm afraid that means i need to completely change my event wiretapping system... (kV has the same issue). so, that definitely goes to the todos, but not for a3.

**Comment by godbout** [comment]
i'm building the third app, to handle scrolls, and i'm having a look at other ways to track events. i think there's a way to make this work for Wooshy too, but i have to check a lot of things, like that it doesn't break integration with Hammerspoon, Hyperkey etc. so just curious: how much is this an issue? does it happen that you're finding yourself having this issue often?

**Comment by AbNull** [comment]
Breaking intergration? Pretty important I geuss. Personally I like to fiddle with things so it wouldn't bother me to start with.

**Comment by godbout** [comment]
ok so now Wooshy can be activated on password fields, and you can search your term, but you can't press enter 😂️

**Comment by godbout** [comment]
solved in Ws14: https://github.com/godbout/Wooshy.docs/releases/tag/14
