### ISSUE TITLE
not working on Notion

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#139]
Weird. I mean the macOS Notion app. Didn't that work before?

**Comment by godbout** [comment]
yes. it used to. i've been dealing with them privately. gonna copy/paste the relevant information. (it's not good.)

**Comment by godbout** [comment]
```
ok so yeah, Notion has broken their AX support. whatever special AX attribute i bomb them with, they don't respond. it does affect not only Wooshy (and kV and Scrolla), but any other app that use the AX, like Shortcat, Vimac, Homerow, etc.

what i'm gonna do on my side now is file a bug report to them. did in the past, never got any answer. quite usual with Electron apps. the issue may be on their own side, the issue may be on the Electron framework itself. i'd recommend you reporting the issue to them also. the more bug reports they receive, the more we're gonna bring attention. and hopefully they'll start caring.

**Comment by godbout** [comment]
"
so i've reached out through Twitter, and Notion support email. there's Discord stuff also but i don't use Discord, and i don't really wanna follow up live with them lol

what i would suggest is that you report also, and maybe connect to their Discord servers. as far as i'm concerned, all the issue is on their side. and it will affect a lot of other apps. once they make their UI pingable through AX again, Wooshy will work. 
"

**Comment by godbout** [comment]
"
been escalating the issue three times to engineers. now they're saying it reached the highest level, so they're gonna look into it but they're closing the issue for now 😂️😂️😂️

so yeah. same as last time. waste of time. sorry."

**Comment by godbout** [comment]
"
ok so they've answered back. so the answer is that if you need Accessibility Support, use a browser, not their app. LOL. good luck.
"

**Comment by godbout** [comment]
the above is a recent talk i had with someone asking about the same issue.

`TL;DR: the Notion app is broken. Notion tells you to use a web browser if you need AX.`

**Comment by roelvangils** [comment]
Okay, thanks! Back to the browser then 😉 Little benefits to use the "app" anyway.

**Comment by godbout** [comment]
> Okay, thanks! Back to the browser then 😉 Little benefits to use the "app" anyway.

it's just very boring tbh how apps, especially the ones that wanna be lazy and use Electron-based framework, just do shit to support Accessibility. it just feels very lazy and misguided to me.

**Comment by roelvangils** [comment]
Absolutely.

**Comment by godbout** [comment]
proof of concept done. now need to implement that properly, and support for Notion will be coming soon. i have a pending release because Paddle doesn't want to enable the Yearly Subs for Wooshy and kV. the code and the sites are ready. just waiting for Paddle to stop being stubborn and i'll release right after.

https://github.com/godbout/Wooshy.docs/assets/121373/1f24a636-42d2-4ddc-b576-e743d26ae3b5

**Comment by godbout** [comment]
Yearly Subs are out. next Notion is coming this week in Wooshy 27.

**Comment by godbout** [comment]
done in Ws27: https://github.com/godbout/Wooshy.docs/releases/tag/27
