### ISSUE TITLE
Make Wooshy be used in scripts (Keyboard Maestro)

### ISSUE THREAD

**Issue by Josh-Piper** [godbout/Wooshy.docs#141]
Hey!

I've been using Wooshy for probably 4-5 months now and absolutely love it. Great application!!! 👍 🚀 

I have created a script in Keyboard Maestro to click on a button that can't be accessed with an application called Webstorm (IntelliJ) and it current works. Big thank you for making Wooshy fast, since I tried doing this about 3 months ago and it didn't work, but now it works very smoothly.
![photo-11-11 at 08 26 47@2x](https://github.com/godbout/Wooshy.docs/assets/35862340/b2974a8d-e7c9-43e2-80f7-01f74254b52b)
![photo-11-11 at 08 29 47@2x](https://github.com/godbout/Wooshy.docs/assets/35862340/8c696496-ef33-4090-9d9f-bd9dbade905b)
![photo-11-11 at 08 30 29@2x](https://github.com/godbout/Wooshy.docs/assets/35862340/2518855d-68a4-4a3b-9712-02ea664f09e8)
![photo-11-11 at 08 30 56@2x](https://github.com/godbout/Wooshy.docs/assets/35862340/dc823edb-12d7-4b02-a4d8-81cf14c85299)

Unfortunately, this script has a bit of latency (between 2-3s) due to the mouse moving and clicking the element etc. I was wondering if there is a way to make Wooshy integrate into scripts and click the button instantenously. Otherwise, do you know how I could scan the accessibility tree and click the button using AppleScript? Or would this not be as efficient as Wooshy due to the scanning?

**Comment by godbout** [comment]
> to click on a button that can't be accessed with an application called Webstorm (IntelliJ)

sorry what do you mean by "a button that can't be accessed". i've tried and i can access those WebStorm buttons from your screenshots with Wooshy.

> ![photo-11-11 at 08 26 47@2x](https://user-images.githubusercontent.com/35862340/282182720-b2974a8d-e7c9-43e2-80f7-01f74254b52b.jpeg) 

Wooshy has custom URLs. see: https://github.com/godbout/Wooshy.docs#custom-urls
you don't need to pretend to press a hotkey and paste something in Wooshy. you should be able to call the proper custom URL to toggle Wooshy and fill it with the text you need. then Wooshy will start the search automatically.

regarding your `command option control` thing, tried also and WebStorm responds to Wooshy normally. i remember someone having some sort of similar issue in the past with KM and the issue was some option in KM that would strip away some key modifiers. maybe it's the case for you too? 🤔️

![photo-11-11 at 08 29 47@2x](https://user-images.githubusercontent.com/35862340/282182988-8c696496-ef33-4090-9d9f-bd9dbade905b.jpeg) ![photo-11-11 at 08 30 29@2x](https://user-images.githubusercontent.com/35862340/282183023-2518855d-68a4-4a3b-9712-02ea664f09e8.png) ![photo-11-11 at 08 30 56@2x](https://user-images.githubusercontent.com/35862340/282183370-dc823edb-12d7-4b02-a4d8-81cf14c85299.jpeg)

Wooshy can click this button. "instantaneously" i doubt so. you need to go through the AX tree to know where to click. or you need to know the UI Element's coordinates to grab it directly (this is how the Accessibility Inspector and Wooshy's Inspector work btw, by grabbing the UI Element at mouse coordinates).

for AppleScript, i did a whole bunch of Alfred Workflows in the past where i tried to use AppleScript, and i can't fucking find any good doc or book about it, or even understand how to find the info myself. i'm not sure if Apple is kinda half-assing the thing or what. i _may_ be possible to grab a window, then its buttons according to titles etc. but 1) not sure 2) it's usually actually pretty slow. so can't help much on that one sorry.

> Unfortunately, this script has a bit of latency (between 2-3s) due to the mouse moving and clicking the element etc. I was wondering if there is a way to make Wooshy integrate into scripts and click the button instantenously. Otherwise, do you know how I could scan the accessibility tree and click the button using AppleScript? Or would this not be as efficient as Wooshy due to the scanning?

the mouse movement and clicking shouldn't take that long. so it's probably going through the AX tree? but still. pretty fast here on my old MBP. 

hope the above clarifies a bit. but honestly there's a lot to unpack, and with the text on pics that i can't quote etc. it makes it a bit harder. to keep the discussion going, let's cut everything into smaller parts and solve them one by one. but please try the custom URLs first, that may already help a bit.

**Comment by Josh-Piper** [comment]
![photo-11-11 at 21 30 25@2x](https://github.com/godbout/Wooshy.docs/assets/35862340/1f4f4c71-f7fd-4c07-8bc1-d6798e3351b8)


Got it working where the button click is less than 1 second. Note I needed to add the delay to make sure the search completes. Still a bit of a delay where I can see the Whooshy UI appears. But its pretty good and is usable.

I ended up having to refer https://github.com/godbout/Wooshy.docs/issues/133 where it mentions you need to use `open -g` instead of `open` for the focused application to remain the same as before the execution, otherwise Whooshy becomes focused. In Keyboard Maestro this was `open in background`.

Might be worth adding this to your README, as it isn't obvious to a beginner like myself to understand these differences.

> sorry what do you mean by "a button that can't be accessed". i've tried and i can access those WebStorm buttons from your screenshots with Wooshy.
Webstorm/IntelliJ didn't have inbuilt shortcuts to allow me to activate these buttons automatically. Nor did it have these actions in the menubar, so I couldn't use a native solution to accessing the buttons, and hence why I'm using Wooshy for this problem.

> regarding your command option control thing, tried also and WebStorm responds to Wooshy normally. i remember someone having some sort of similar issue in the past with KM and the issue was some option in KM that would strip away some key modifiers. maybe it's the case for you too? 🤔️
Given I have a working solution at the moment, I don't really mind this haha

I just assumed Wooshy used AppleScript, are you natively finding all the buttons or using OCR?

Appreciate the help btw, finding about these custom url's was a worthwhile rabbit hole.

**Comment by Josh-Piper** [comment]
Circling back to making the button click instaneous, I am confused why it's not possible if we know what the button/text is.

I made this thread in the Keyboard Maestro forum about AppleScript to solve the problem https://forum.keyboardmaestro.com/t/intellij-how-to-select-element-whose-label-is-process-console-debugger-etc/33954/9 and it sounds like the solution is looking bleak.

I am honestly confused how Wooshy differs from AppleScript and how it finds the different buttons. Shouldn't AppleScript and Swift be pretty much the same when traversing the accessilibity the API's? 

A person in the Keyboard Maestro forum mentioned that AppleScript doesn't find buttons in IntelliJ well/not always possible, but it looks like Wooshy finds most of them?

**Comment by godbout** [comment]
> Got it working where the button click is less than 1 second. Note I needed to add the delay to make sure the search completes. Still a bit of a delay where I can see the Whooshy UI appears. But its pretty good and is usable.

hmm maybe the delay to open Wooshy comes from KM, because from the Terminal it's instant. at least for me.

> I ended up having to refer #133 where it mentions you need to use `open -g` instead of `open` for the focused application to remain the same as before the execution, otherwise Whooshy becomes focused. In Keyboard Maestro this was `open in background`.
> 
> Might be worth adding this to your README, as it isn't obvious to a beginner like myself to understand these differences.

yeah that's kinda out of Wooshy's scope tho. you could call the custom URL without `open -g`. it's just one case out of many different ways to call the custom URLs. so people who dig and dive into there are expected to know a little what they're doing 😂️

> 
> > sorry what do you mean by "a button that can't be accessed". i've tried and i can access those WebStorm buttons from your screenshots with Wooshy.
> 
> Webstorm/IntelliJ didn't have inbuilt shortcuts to allow me to activate these buttons automatically. Nor did it have these actions in the menubar, so I couldn't use a native solution to accessing the buttons, and hence why I'm using Wooshy for this problem.
> 

oh ok, got you.

> I just assumed Wooshy used AppleScript, are you natively finding all the buttons or using OCR?

no AppleScript. it's too slow, not testable, etc. AppleScript is just to make some sort of basic automation. definitely not Wooshy's work. it's not OCR either. OCR is slower. it has other benefits tho. for example in PDFs Wooshy can't read the text. OCR can. but Wooshy can read a lot of metadata that is hidden behind UI Elements, OCR cannot. there's at least one app that i know that does a little bit what Wooshy does but through OCR. might be worth having a look: https://superkey.app

> Appreciate the help btw, finding about these custom url's was a worthwhile rabbit hole.

it's in the docs but i'm also known to be very available, so people drop messages here or by email. feel free when you have questions etc.!

**Comment by godbout** [comment]
> Circling back to making the button click instaneous, I am confused why it's not possible if we know what the button/text is.

to generate a click you need to set the mouse location. to know the mouse location you need to know which UI Element you want to go to. to know which UI Element you need to go to you need to scan through UI Elements data. this takes some time. the time where you see the loading icon in Wooshy and the time it takes to highlight the Targets.

> I am honestly confused how Wooshy differs from AppleScript and how it finds the different buttons. Shouldn't AppleScript and Swift be pretty much the same when traversing the accessilibity the API's?

well, i don't understand what you're asking here. like Swift and AppleScript are two different technologies, for two different purposes. the Accessibility Framework is something else altogether. plus i don't have enough internal knowledge of AppleScript works (not even external knowledge actually lol). not sure if it's the case already but if you start designing apps for the Mac you'll find that Apple gives you a whole bunch of good nails and screws, but also things are messy. for their own apps they even have private APIs that we can't (at least easily) use so for example the Accessibility Inspector has features that we can't reproduce. how AppleScript is done internally i have zero idea.

> A person in the Keyboard Maestro forum mentioned that AppleScript doesn't find buttons in IntelliJ well/not always possible, but it looks like Wooshy finds most of them?

again. maybe. i'm not sure about AppleScript. and AppleScript is slow. Wooshy grabs UI Elements exposed by an application. if that application does a good job, then Wooshy can target those Elements. that's about it.

**Comment by Josh-Piper** [comment]
Fair points about what is out of Whooshy's scope. Appreciate the help :) Seems like AppleScript is just inferior to using Swift haha

**Comment by godbout** [comment]
> Fair points about what is out of Whooshy's scope. Appreciate the help :) Seems like AppleScript is just inferior to using Swift haha

hmm not sure i'd personally would call it "inferior". it's just different technologies for different purposes. AppleScript allows people who have no knowledge or no interest in low level coding to build a bunch of stuff for themselves. and it seems pretty good with this. Swift is another thing altogether. low level (not the lowest tho) where you have closer access to macOS bolts and nails. to give you a (bad) analogy, it's like if AppleScript is Wordpress. allows you to do a blog quickly, etc. without knowledge of more lower level HTML, CSS and JavaScript, which would be Swift. with HTML, CSS and JavaScript yes you can rebuild Wordpress yourself, but that's not the point. so both have their own target audience. i'd actually like to know AppleScript better, but i've never really found good documentation. also there's kinda AppleScript through JavaScript so it's confusing. and i don't know if Apple is continuing building in that direction. so yeah. i build full apps instead 😂️

**Comment by godbout** [comment]
https://stackoverflow.com/questions/62309426/is-applescript-a-dead-language#:~:text=1%20Answer&text=The%20whole%20AppleScript%20stack%20has,t%20for%20quite%20some%20time.
