### ISSUE TITLE
Not working on Superhuman

### ISSUE THREAD

**Issue by jondkinney** [godbout/Wooshy.docs#143]
Doesn't seem to find anything anywhere in the UI

**Comment by godbout** [comment]
thought it was supported. lemme check.

**Comment by godbout** [comment]
yep. used to be supported. still is somehow, but Superhuman doesn't seem to respond to AX enforcement calls. maybe they broke their own AX tree. wouldn't be surprising coz it's a shit Electron thing. will have to investigate further.

**Comment by godbout** [comment]
i'm thinking it's the AX tree broken because other apps don't work on it either anymore.

**Comment by godbout** [comment]
so yeah, in the latest versions of Superhuman they did a really shit job. basically they broke their AX tree so Wooshy can't transverse the app and get all the UI Elements. it used to work. it's possible that it's because they use a new version of Electron? which is a massive shit thing. anyways. devs have been contacted. let's see if they can fix that, because basically that will make Superhuman stop working with any Accessibility tool, which is pretty bad.

**Comment by godbout** [comment]
i'm in heavy discussions with the Superman team and they're super responsive. not sure if they can fix but it's super appreciated. i'll update when i have news.

**Comment by godbout** [comment]
found a way to make Superhuman work. coming in the next release.

**Comment by godbout** [comment]
added in Ws28: https://github.com/godbout/Wooshy.docs/releases/tag/28
