### ISSUE TITLE
not working on Microsoft Teams (work or school)

### ISSUE THREAD

**Issue by evendaniel** [godbout/Wooshy.docs#147]
Doesn't work with the recent update to the teams application. Nothing is selectable.

**Comment by godbout** [comment]
used to work? will check, thanks.

**Comment by evendaniel** [comment]
It worked with the older version of the teams app on mac, for the new teams mac app it does not. It is a separate download from the older teams app.

**Comment by godbout** [comment]
there's a tendency in shit apps nowadays to just have the macOS window native, then a split, then have the custom UI separated from the rest, which basically splits the Accessibility tree and render it useless. been seeing this in a couple of apps unfortunately. no tools that goes through the AX tree can do anything. we thought the old Electron framework was the worst but multiplatform people came with something even worse lol

**Comment by evendaniel** [comment]
So, might be SOL for wooshy support for new teams app? Really is a shame that these tools are being built that way.

**Comment by godbout** [comment]
OH> so if Shortcat works, then it's not an issue with the broken AX. might be then that i need to add support specifically for that new app. i build an App Catalog because 1) it helps keeping Wooshy and your Mac unbloated 2) i need the App Catalog anyways for one of my other app so it's shared. i'll check very soon (in the next hours) and let you know.

**Comment by godbout** [comment]
a thousand sorry. that'll teach me to say i'll check in the next hours and not adding this in the TODO list. bear a little bit more with me and i'll come back to you soon for the update on the first investigation.

**Comment by godbout** [comment]
ok so i had a first try. yeah, Wooshy can only find the title bar. but all the other apps i've tried have the same issue: Vimac, Homerow and **Shortcat**. which would make sense if the AX Tree is broken. which version of Shortcat are you using? i'm using the latest one. sure you've tested again that new Teams? it's weird. if it indeed does work well that means there would be something to do. i'll investigate more but it'd help if you lemme know. thanks!

**Comment by godbout** [comment]
![Screenshot 2024-01-17 at 17 48 24](https://github.com/godbout/Wooshy.docs/assets/121373/a69750b4-1000-4ca5-99a8-8d8d72a867e6)

so i'm able to get it to work, but i can't confirm yet that i can every time 😂️ the issue is basically i'm testing when a client is asking for a meeting through Teams. i don't seem myself to have the possibility to start a meeting and spend some time doing my tests. any chance that we have some fun and you start a meeting for me to join? 😂️ shouldn't need long to confirm what needs to be done. i'm having a strong idea already. just need a confirmation to keep Wooshy as small and fast as needed. thanks.

**Comment by godbout** [comment]
ok so Wooshy's way to expose the AX Tree doesn't work for Teams. but somehow it is possible to force Teams to expose it because one Shortcat does it, all the UI Elements are available to Wooshy. so i'm not sure how Shortcat does it, but it's possible 😃️ more investigation on the way!

**Comment by godbout** [comment]
just to let you know that this is taking most of my nights 😂️😂️😂️
obviously there's something magic with Teams. the AX is not exposed UNTIL you do something. but i don't know what. VoiceOver opens Teams up. the Accessibility Inspector too. i know Apple has some private APIs with the AX Framework, which made me wonder if this is what they're using. BUT the fact that Shortcat is able to get Teams to open up too means there's a way. just haven't found it yet, but deeply playing with this 😅️ so no ETA, but most probably will happen, yes. and thanks. that'll make my AX apps better, including Wooshy, and will improve my AX Framework's knowledge. very good investment of time and energy.

**Comment by godbout** [comment]
ok so after three weeks Microsoft posted a default shit answer to my post. but i've found someone with the question on another forum: https://feedbackportal.microsoft.com/feedback/idea/94110324-4c7d-ee11-a81c-0022484e5453

can't post or like tho, even logged in. this is so, so, so shit 😂️😂️😂️
will keep checking if something comes up on that forum.

**Comment by godbout** [comment]
still looking into this. driving me nuts 😂️

**Comment by godbout** [comment]
Uploading Screen Recording 2024-07-03 at 17.59.27.mov…

FINALLY!!! took only 6 months of reverse engineering.

**Comment by godbout** [comment]
just a poc for now. will fine tune, clean, and coming in a very soon release. (kinda blocked now waiting for Paddle to handle some sub shits.)

**Comment by godbout** [comment]
done in Ws24: https://github.com/godbout/Wooshy.docs/releases/tag/24
