### ISSUE TITLE
not working on Insomnia

### ISSUE THREAD

**Issue by TCattd** [godbout/Wooshy.docs#15]
This: https://insomnia.rest

Maybe the same as https://github.com/godbout/Wooshy.docs/issues/8 ?
As both of them are Electron based apps.

**Comment by godbout** [comment]
yes!

so there's a reason why: Electron apps don't have their Accessibility enabled by default. testing if an app is an Electron one is a bit of a hit-and-miss. one way to "solve" this would be to blast any app with some special AX attributes. that would make all Electron apps work, but 1) that would be a waste of resource 2) that breaks window manager apps 3) that's dirty.

on another hand, i'm already keeping an App Catalog for [kindaVim](https://github.com/godbout/kindaVim.docs) because kV is so complex that i need to curate the apps to give hints to users. so i'm using the same Catalog for Wooshy. once an app is curated, the job is done. so it's growing over time for good.

so please, if you find any app that doesn't work, just report. and i'll add them quickly. once it's done it's done. thanks!

**Comment by godbout** [comment]
i've known Insomnia for a long time (not a user) but only know i'm realizing Insomnia + REST ahhahhahahhahah so good.

**Comment by godbout** [comment]
added in a4: https://github.com/godbout/Wooshy.docs/releases/tag/1a.4

enjoy.
