### ISSUE TITLE
not working on Local WP

### ISSUE THREAD

**Issue by TCattd** [godbout/Wooshy.docs#17]
Local WP https://localwp.com/releases/

**Comment by godbout** [comment]
not sure whether you've heard about [kindaVim](https://github.com/godbout/kindaVim.docs) or if you have any interest, but Local and Bitwarden are two Electron apps that work perfectly with kV. that's because they implement the macOS Accessibility properly, and that is very, VERY rare for Electron apps. great ones 👍🏼️

**Comment by godbout** [comment]
added in a4: https://github.com/godbout/Wooshy.docs/releases/tag/1a.4

closing. please reopen if any issues.
