### ISSUE TITLE
not working on Spotify

### ISSUE THREAD

**Issue by TCattd** [godbout/Wooshy.docs#19]
Spotify https://www.spotify.com/us/download/mac/

**Comment by godbout** [comment]
i'm having troubles with this one. it's an Electron app but setting the Electron special AX attribute doesn't work. but i'm sure it's possible to get Spotify to be accessible. will have to contact the devs.

**Comment by godbout** [comment]
ok that was a tough one, but Spotify coming in a7. :cool_sunglasses:

**Comment by godbout** [comment]
a7 out: https://github.com/godbout/Wooshy.docs/releases/tag/1.a7

**Comment by godbout** [comment]
shit, it's not working.

**Comment by godbout** [comment]
seems it's intermittent. so i guess you'll have to wait for a8 😬️

**Comment by godbout** [comment]
if it doesn't work from the first start, try to quit the app and start again. or hide/show. let me know your experience. seems here that sometimes it works, sometimes it doesn't. pretty sure this is fixable.

**Comment by godbout** [comment]
so in my case if i'm using just my MBP screen it doesn't work well. but if i connect to an external monitor Spotify catches the AX request well. it's pretty nightmarish to handle. using two screens at the same time doesn't work well either.

let me know in your case how it goes, so that i can find a better solution. thanks.

**Comment by godbout** [comment]
should now be working well: https://github.com/godbout/Wooshy.docs/releases/tag/1a.8

please reopen if not. thank you!
