### ISSUE TITLE
Notion Enhanced: Entire window highlighted

### ISSUE THREAD

**Issue by archetyped** [godbout/Wooshy.docs#39]
When activating Wooshy in [Notion Enhanced](https://github.com/notion-enhancer/desktop), the entire window is highlighted as the first result for many searches (example: searching for text on page).  The highlight obscures the entire window and also does not have any effect when selected by hitting `return` key.

* Wooshy version: 1a6
* Note: Notion in web browser does not exhibit the same issue.

## Screenshot

![Wooshy_1a6_Full window highlight](https://user-images.githubusercontent.com/3237917/181837995-443339c7-2bab-46b1-b8b9-c6db5c0042b4.png)

**Comment by godbout** [comment]
those fucking Electron apps are gonna kill me. 0 respect for standard. they're using the wrong type of element to contain the other elements. that big one is defined as a text area rather than a group. i need to target text areas. will have to find a way to tweak the engines without breaking stuff for apps that behave. what a pain. but will check.

**Comment by godbout** [comment]
improved in a7. will probably come by tomorrow.

**Comment by godbout** [comment]
this is fixed in a7: https://github.com/godbout/Wooshy.docs/releases/tag/1.a7

but i think there's possibility to get more targets on Notion. it's just painfully badly built.

**Comment by godbout** [comment]
like currently Wooshy grabs the whole buttons in the sidebar, but i think we should be able to grab the disclosure element, the icon, and the text separately.

![Screenshot 2022-08-01 at 15 48 22](https://user-images.githubusercontent.com/121373/182099651-4f93edba-71e8-4305-af4f-9b3d786067c0.png)

but that requires more investigation, because it's not built in a standard way.

**Comment by godbout** [comment]
closing for now as the mega text area is not removed.
