### ISSUE TITLE
Feature request: support for ⌘+C

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#51]
I just thought of another use case for Wooshy: copying text.

Say, I select this paragraph. I don't want to click it, but just want to copy the text to the clipboard. 

<img width="625" alt="20220807_222031_Safari@2x" src="https://user-images.githubusercontent.com/103744/183309628-f279f042-7dfa-43a1-bb96-e78d7371d2d1.png">

What do you think?

**Comment by godbout** [comment]
> Say, I select this paragraph. I don't want to click it, but just want to copy the text to the clipboard.

how do you select the text?

Wooshy doesn't select text, it clicks on areas. so there's really no way to "copy text". although you could right click with `control return`, and go through the menu and choose `copy`.

[Superkey](https://superkey.app) deals with text (through OCR) while Wooshy deals with UI elements positions/size through the Accessibility APIs. so maybe Superkey could do what you want?

also, as asked above, not sure how you select text. but once it's selected, you could also use the new [Alfred Universal Actions](https://www.alfredapp.com/universal-actions/) like you can copy the text and do a million other things on it. pretty neat.

**Comment by roelvangils** [comment]
I selected that paragraph by typing a word or a few characters that appear in that paragraph. Wooshy allows you to select any element, even if it's not interactive. So, I figured: if Wooshy allows me to select that paragraph like this, it must be able to copy the text of that paragraph (which is exposed in the accessibility information) as well.

**Comment by godbout** [comment]
Wooshy doesn't select the text :D it looks like it, but it draws over the box's position and size. the idea is clicking within that box. i guess it could be possible to mix Wooshy and kindaVim, but that's another project. Wooshy isn't dealing with text the way kV does.

or i'm wrong and i don't even know myself how Wooshy works 😂️
but selecting the text that is within a box, it's a total different thing. and i believe other tools will do a way better job. coz now it's copy, but later it could be send the text by email, etc, etc. lots of apps already do that.

**Comment by roelvangils** [comment]
Fair enough! I know Wooshy doesn't select the text when it finds it, but it does now what the text is, so it _could_ technically "copy" it. Right? 🙂 But I understand that is out of scope for this app!

**Comment by godbout** [comment]
> Fair enough! I know Wooshy doesn't technically select the text when it finds it (it draws a rectangle around it), but it does now what the text is, so it _could_ technically "copy" it too. Right? 🙂 But I understand that this is out of scope for this app!

aaaaaahhhhhh yes, i see. glad you're pushing. my head has been a little overwhelmed. why i was saying it can't copy is because of how Wooshy works behind the scenes. it combines all the texts together, including the one you cannot see (the other Accessibility metadata), for searching purposes. it could be possible to split the texts and have them individually. but then you have another issue, which is to know which text is actually showing on the screen. for example for buttons, it's the title. but for static text, it's the value. but sometimes it's the label, etc. so i'm not sure we can get it 100% right, and even then things may have to be custom on a per role basis. which, again, could be technically possible. it's just a big modification of the engines, coz it was not done for that.

but i do like the idea. thanks again for pushing. what do you think the keyboard shortcut could or should be? `command c` while on The Input?

**Comment by godbout** [comment]
i kinda really like the idea 😂️

**Comment by roelvangils** [comment]
Haha! Yes, the good old <kbd>⌘+C</kbd> would work fine, I think. But I understand the complexities. It's certainly not a must-have (at least not for me). Thinking a bit more about it, maybe you could also add support for <kbd>⌘+A</kbd> to *really* select the text inside the of focused area (it it's selectable text, of course).

**Comment by godbout** [comment]
i guess there could be something like if you press `command c` while you're in Wooshy's Input and you haven't selected text within it then it copies the content of the UI element yes.

`command a` would be another thing altogether. `command c` could be possible because i would just have to paste some AX info to the clipboard. but `command a` would require some other kind of technology. not even sure it's possible for static text.

**Comment by fennelcakes** [comment]
Came here looking for this, wanted to throw support behind the request!

In the meantime, you can get an imperfect workaround for this simulating a triple-click combined with  Wooshy's "move the mouse without clicking"  (`shift command return` by default). BetterTouchTool (or, I'm assuming, KeyboardMaestro) can do this. In BTT, when you create your action, `Custom Mouse Button and Modifiers` -> `Click Type: Left Triple Clck`. Then `Cmd + C` to copy.

This selects entire paragraphs, so it's not as accurate as Wooshy can be. But I just thought it was a good way of taking advantage of Wooshy's ability to just move the mouse and do nothing else. I see that double clicks are on the roadmap, don't know if implementing a triple click is worth it compared to just a straight `command c` like you all described.

I'm currently on version `1a18` btw.

**Comment by godbout** [comment]
@fennelcakes i'll come back to you later, but i definitely can't ignore your comments. not with that kind of username.

**Comment by godbout** [comment]
> In the meantime, you can get an imperfect workaround for this simulating a triple-click combined with Wooshy's "move the mouse without clicking" (`shift command return` by default). BetterTouchTool (or, I'm assuming, KeyboardMaestro) can do this. In BTT, when you create your action, `Custom Mouse Button and Modifiers` -> `Click Type: Left Triple Clck`. Then `Cmd + C` to copy (attach Cmd + C as an additional action in BTT or do it manually)

i was wondering what "workaround" you were talking about but i guess it's for the `command a` right?

> This selects entire paragraphs, so it's not as accurate as Wooshy can be.

well in any case the idea was to get the whole text, not just what is typed. basically Wooshy targets a UI element, in that UI element you have the whole text. pressing `command c` would copy that text, not just the part you typed in the UI. anyways that's the current idea at least. if it's an image, or something without text like a menu icon, then i'd copy some metadata behind.

> But I just thought it was a good way of taking advantage of Wooshy's ability to just move the mouse and do nothing else. I see that double clicks are on the roadmap

good that you bring this up. the reason why i haven't done the `double click` yet is 1) i've found i never need it. usually when i need it what i learned to do is `command o`. works in a lot of places. 2) i feel like the `double return` kinda suck for a double click, and i haven't found something that feels right. triple click would be even more hideous 😂️

> EDIT: Just realized, you can add `shift command return` to the BTT action sequence, so you can make a sequence/shortcut to move the mouse with wooshy, triple click, then copy. (so, type in your selection in Wooshy first, then type your sequence, so long as it's a sequence that doesn't exit wooshy)

cool. so you can already achieve what you mentioned above using BTT? i guess i need to start looking at those tools because they seem to combine well with kV/Wooshy and that'd allow me to better guide users (but also i think i'm too stupid ☹️)

**Comment by fennelcakes** [comment]
> cool. so you can already achieve what you mentioned above using BTT? i guess i need to start looking at those tools because they seem to combine well with kV/Wooshy and that'd allow me to better guide users (but also i think i'm too stupid ☹️)

Sort of! It's a little too quirky and inconsistent with my method. Some limitations:
- What's highlighted by Wooshy isn't necessarily what's going to be selected by the triple click action. That's why I said that Wooshy is more "accurate" in the sense that you have more control over what's under the highlight.
- If there's a link somewhere in your selection, Wooshy might place the cursor over that link. Then the BTT sequence will just click through it instead of triple clicking, selecting, and copying it.
- Depending on where your mouse is initially, before your Wooshy search, the BTT sequence might be too fast and start triple clicking before Wooshy can move the mouse to its final position, so you get a very weird mouse selection by the end.

If you split this sequence into two shortcuts (move the mouse with Wooshy's `shift command return` and *then* do a BTT sequence of triple click and `Cmd + C`) then you might have more control over what you're selecting and copying. But it still won't be what OP asked for as far as implementing `Cmd + C` over Wooshy's highlight, or at least when it does achieve the same result, it'll be by accident and happen inconsistently. I'm sure there's ways to fine tune this but I'm not a BTT/Keyboard Maestro expert.

In any case, Wooshy is too cool and powerful and I was being greedy by trying to integrate it into every aspect of my workflow at the moment. OP might want to check out [SurfingKeys](https://github.com/brookhong/Surfingkeys) and its visual mode selection to achieve mouseless selection/copying in a browser, but with less speed than what Wooshy would provide.

**Comment by godbout** [comment]
> * If there's a link somewhere in your selection, Wooshy might place the cursor over that link. Then the BTT sequence will just click through it instead of triple clicking, selecting, and copying it.

yeah. same issue with icons, etc.

> * Depending on where your mouse is initially, before your Wooshy search, the BTT sequence might be too fast and start triple clicking before Wooshy can move the mouse to its final position, so you get a very weird mouse selection by the end.

> If you split this sequence into two shortcuts (move the mouse with Wooshy's `shift command return` and _then_ do a BTT sequence of triple click and `Cmd + C`) then you might have more control over what you're selecting and copying.

can't do that with your current setup? i think for what OP is talking about i think the idea is good, but i'm still digesting how to implement this properly. because each UI Element may show different info on the screen, so it's not really straightforward. also overriding usual commands (like `command c`) is always a little tricky so i'm not sure. (technically it's fine, but people usually get confused because the behavior is unexpected.)

> In any case, Wooshy is too cool and powerful and I was being greedy by trying to integrate it into every aspect of my workflow at the moment.

😅️ i think there should be quite a big potential combining Wooshy with the other tools (KE, HS, BTT, KM, etc.). i'm just not personally much into it, but i feel people are starting doing cool things with them.

**Comment by fennelcakes** [comment]
> 😅️ i think there should be quite a big potential combining Wooshy with the other tools (KE, HS, BTT, KM, etc.). i'm just not personally much into it, but i feel people are starting doing cool things with them.

Yep I was just sharing some ideas to help someone who might be interested enough to make it work. Thanks for making such a cool app! Please focus on what you feel its strengths are!

**Comment by godbout** [comment]
always feel free to dump your thoughts in the [Discussions](https://github.com/godbout/Wooshy.docs/discussions) too. from my experience with kV, people tend to gather and come up with super nice stuff that i end up implementing and had no idea about to start with 😅️ very cool.

**Comment by godbout** [comment]
done in a21: https://github.com/godbout/Wooshy.docs/releases/tag/1.a21
you can copy text, or metadata.

**Comment by roelvangils** [comment]
Hi @godbout! Thanks for implementing this! 🙏 This feature allows you copy things that normally cannot be selected or copied (without using OCR):

https://user-images.githubusercontent.com/103744/188904307-109fe71c-9d49-4f69-a357-82662f84900d.mp4

Very nice! The only thing that does not work for me is copying the metadata...

**Comment by godbout** [comment]
well, the metadata has to be relevant to the field you copy. for a link, it's gonna be its URL. for a checkbox, it's gonna be its status. for a static text... there's no metadata, so it copies the text.

what were you expecting here?

**Comment by godbout** [comment]
see: https://www.youtube.com/watch?v=m2KpXtRnQWE

**Comment by roelvangils** [comment]
Cool! I didn't know what to expect, but it makes total sense now.

BTW: I love [Air](https://en.wikipedia.org/wiki/Air_(band))! 🎵
