### ISSUE TITLE
Accessing items currently hidden from view

### ISSUE THREAD

**Issue by hasantahir** [godbout/Wooshy.docs#53]
Not sure how to describe it, but is it possible for Wooshy to access items that are initially hidden from view? 

https://user-images.githubusercontent.com/11236148/183446684-a4497d27-f032-40b8-bb15-5e0fe7f45ac0.mov

For example, in the screencast below, I need to make the menu visible to bring up the `Save As...` option. Would be incredible if Wooshy were to access these hidden corners.

Cheers

**Comment by hasantahir** [comment]
Another instance where this could be helpful is when a user needs to scroll up or down:

https://user-images.githubusercontent.com/11236148/183449181-e53608d5-06a7-4050-9fdb-9e61beb23a82.mov

**Comment by godbout** [comment]
> Not sure how to describe it, but is it possible for Wooshy to access items that are initially hidden from view?
> 
>  Wooshy.mov 
> 
> For example, in the screencast below, I need to make the menu visible to bring up the `Save As...` option. Would be incredible if Wooshy were to access these hidden corners.
> 
> Cheers

this will be coming after v1: https://github.com/godbout/Wooshy.docs#v1
there will be another mode that comes without The Input stealing focus. the issue you're having now is that when you show The Input, the rest of the UI reacts to this. so we need a mode without an Input, where you just type. so you can press the arrow, and then keep typing. the "hidden" views may not be accessible before you press the arrow. i don't know especially in this case, but some views will be generated dynamically.

also, especially for browsers and Electron apps, they may have A LOT of elements outside the view. that slow things down like crazy. so anything that is not within view, is filtered out. Wooshy grabs what you seen on the screen, i don't think it will ever bother with what's hidden. not even menu items.

**Comment by godbout** [comment]
> Thanks. The case in the second video is interesting as Wooshy calculates the location correctly as if we were at the top of the page. The instances at the top are detected yet even though the `Comment` button is disabled, isn't. Later in the video, the instances are highlighted correctly at their location when the window is scrolled up.
> 
> Wondering, how Wooshy knows of the instances as in the first half of the video, even if the instances were hidden.

i don't think that's what happened 😅️

wait. coming back with a video.

**Comment by godbout** [comment]
i think this is what happened:

https://user-images.githubusercontent.com/121373/183464262-e0f03a47-8c90-4818-92d1-b5ad1709fe0a.mp4

look at the position of those three elements in your video. they fit perfectly the top. it's because the search has been done on the top. it doesn't fit the bottom at all. it _looks_ like it fits the text area at the bottom, because of GitHub's design. it's a coincidence.

if i'm wrong, then show me another video. because in your video we don't see that you start the search at the bottom 😄️ so i think you started it inadvertently at the top, then scrolled down.

**Comment by godbout** [comment]
clearly when there's a scroll i should hide the the Targets and maybe also The Input. i've written this down already.

**Comment by hasantahir** [comment]
Great, indeed the same happened in my misleading capture of the second video :-).

**Comment by hasantahir** [comment]
Further thought:

If Wooshy can access the hidden elements, I think it could be **transformative** in how we use keyboard shortcuts. Now that there are so many, it's hard to memorise them. With Wooshy, a terse description could lead to the target. 

For example in MS Word, we need to perform an extra step to navigate to the Tab containing the desired targets and then hit the targets. 

https://user-images.githubusercontent.com/11236148/183641724-f03f8384-53e6-4dac-a572-680b80ce27e2.mov

Perhaps down the road, is it possible?

**Comment by godbout** [comment]
> Perhaps down the road, is it possible?

to stay speedy, Wooshy deliberately finds the Targets that are visible, in the frontmost app.

here is what happens when i grab all the elements (visible and not visible) of ONLY THE FRONTMOST APP: 
* https://github.com/godbout/Wooshy.docs/issues/2
* https://github.com/godbout/Wooshy.docs/issues/4

in some cases it takes like 5 minutes to grab all the info. and that's just for the frontmost window. if you want to add any window on the screen, forget it.

but even all the elements of the frontmost window, that'll be a no no sorry. can't keep the app speedy, and a completely different extra work/engine.

there's an app that grabs menu items of the app menu bar, maybe that will return some of the stuff you're talking about in Word? not sure: https://appmakes.io/paletro
there's also Shortcat that does the same thing: https://shortcat.app

grabbing the menu items wouldn't be hard, but that means Wooshy would need to show a list of results à la Alfred, which i don't want.

**Comment by hasantahir** [comment]
Thanks for the feedback. I didn't know of paletro; tried shortcat but didn't digest the idea of so many text labels on the screen. Wooshy has felt quite natural from the start.

**Comment by godbout** [comment]
how is Paletro doing for your issue? does it access what you need? i'm pretty sure it can only access the menu items of the app menus bar. so that would mean that basically it's up to the developer of the apps (in your case, Microsoft) to develop the tab buttons/options into menu items. so that would be a very risky project to do (even if it was out of Wooshy) because it relies on a big thing that is out of our control.

if it was speedy enough, i guess you could scan all the UI element yes. but then after that you would still need to "find" them in order to click for them. like if an element is on another tab, when you select that element, the app would need to go click on its parent first (tab? button? link?) and then click on the selected element. or even not only its parent but its parentS. so it's a crazy engine to build. definitely not Wooshy. feels more like a [kindaVim](https://github.com/godbout/kindaVim.docs) type of project (years of engine development before it being usable). 

but in any case, i don't even think it's worth because of the speed issue.

**Comment by godbout** [comment]
btw, Raycast also has the menu items functionality: https://twitter.com/raycastapp/status/1414973367178891271

**Comment by hasantahir** [comment]
I haven't tried paletro yet but slowly starting to get a feel of Shortcat. Although the Raycast feature got suggested is also similar to Short cat's, it's the number of options presented on screen that take up quite a significant amount of screen real estate.

Will try out Paltero.

**Comment by godbout** [comment]
👍🏼️ good luck!
maybe if you have time also you may want to build your own 😂️

**Comment by chendo** [comment]
@hasantahir With Shortcat, you can change when the hints show up in the options. Shortcat is designed so that you begin typing immediately upon activation, so if you're using it as it was designed, you won't see a huge amount of labels. I'll add options for query window size at some point

**Comment by godbout** [comment]
> clearly when there's a scroll i should hide the the Targets and maybe also The Input. i've written this down already.

so in a16 once The Input is shown you'll not be able to scroll anymore. so no more of this kind of confusion.

**Comment by godbout** [comment]
> so in a16 once The Input is shown you'll not be able to scroll anymore. so no more of this kind of confusion.

actually changing this to you're able to scroll but then The Input and the Targets disappear. i liked blocking the scroll, but i think it may confuse users as why macOS doesn't respond to their scrolling. may change later.

**Comment by hasantahir** [comment]
Thanks, @godbout and @chendo for the feedback. Haven't tried Shortcat beyond a taster session. Can't really understand the meanings of the codes/labels that pop up. 

For Wooshy, would prefer a setting that would lock the scroll (may be an option).

All the best to both of you on the fantastic apps. I think with projects like these, computers are more accessible to use in general, especially for people with RSI and other mobility issues.

**Comment by godbout** [comment]
> For Wooshy, would prefer a setting that would lock the scroll (may be an option).

noted. will digest and see.

> All the best to both of you on the fantastic apps. I think with projects like these, computers are more accessible to use in general, especially for people with RSI and other mobility issues.

@chendo is the one who started it all! respect to the master.

**Comment by godbout** [comment]
> For Wooshy, would prefer a setting that would lock the scroll (may be an option).

coming in a21, as an option.

**Comment by godbout** [comment]
21 out, with the prevent scrolling option: https://github.com/godbout/Wooshy.docs/releases

**Comment by hasantahir** [comment]
Awesome, thanks
