### ISSUE TITLE
Text Field and Targets called Text

### ISSUE THREAD

**Issue by hasantahir** [godbout/Wooshy.docs#54]
In the very rare case when a target is called `Text` as in the screenshot below, Wooshy gets confused and highlights all the text fields:

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/11236148/183459467-c46f8407-fe61-44ff-bc68-72772feb7be1.png">

**Comment by godbout** [comment]
so the reason for this is because you can search Targets by their `role`. `role`s include checkbox, tickbox, switch, link, button, text, text area, text field, etc.

so yeah, searching for "text" is gonna to bring up many Targets. is there any way that you can avoid searching for "text" and use something else instead? should the `role` be an option for the search? i personally use this a lot. for example many times you have a checkbox, you will also have some text associated. to pinpoint exactly what i need, i would do `mark chec` for the checkbox or `mark li` for the link.

**Comment by hasantahir** [comment]
Thanks for the pointer, `link text` and even `li tex` leads me to the target.

**Comment by godbout** [comment]
EXCELLENT! :D

i have a hard time explaining how it "works" in the README, but once you get used to it i think you're gonna love it :D
with a few keystrokes you can indeed reach your specific target!
