### ISSUE TITLE
not working on Firefox Developer Edition

### ISSUE THREAD

**Issue by caffo** [godbout/Wooshy.docs#58]
I can't get all items from the screen highlighted. I only get highlights for some of the items

<img width="2560" alt="CleanShot 2022-08-16 at 16 17 06@2x" src="https://user-images.githubusercontent.com/456/184963880-91a8d7fe-686d-4bfa-8cd7-dcc819bd7b81.png">

Is there a way to get all the things? Is this a bug?

**Comment by caffo** [comment]
Upon more investigation, it looks like wooshy isn't working properly with firefox. If I use it with other apps (like slack), it works. 

But I still would like for it to get items from all visible windows, not only the foremost app. Doable?

**Comment by godbout** [comment]
edited the title. issue is with Firefox Developer Edition, not Wooshy :D

**Comment by godbout** [comment]
> Upon more investigation, it looks like wooshy isn't working properly with firefox. If I use it with other apps (like slack), it works.

some apps require some special Accessibility to be set in order to work. Firefox is supported, but not the Firefox Developer Edition it seems (probably a different bundle identifier). will check and add.

> But I still would like for it to get items from all visible windows, not only the foremost app. Doable?

see the my comments on this thread starting from there: https://github.com/godbout/Wooshy.docs/issues/53#issuecomment-1209288537

basically 1) too slow 2) how would you show the results anyways? lists? don't want that in Wooshy. in that case [Shortcat](https://shortcat.app) is probably a better fit. only show the Targets visible of all visible windows? you still need to iterate through all of them to filter them out. too slow.

**Comment by caffo** [comment]
Thanks for your answers, @godbout. Looking forward to having Firefox Developer Edition added -- it's my daily driver and would make a huge difference for me. I really like using Wooshy!

**Comment by godbout** [comment]
i've added it for a17. should be out in a few days.

**Comment by godbout** [comment]
i meant in a few hours it seems. available in a17: https://github.com/godbout/Wooshy.docs/releases/tag/1.a17
actually a17 is just for that 👀️
enjoy.

**Comment by caffo** [comment]
That's perfect, thanks!

**Comment by godbout** [comment]
✌🏼️
thanks for taking the time to ask. makes Wooshy better.
