### ISSUE TITLE
not working on Asana

### ISSUE THREAD

**Issue by dudunato** [godbout/Wooshy.docs#6]

**Comment by godbout** [comment]
very strange, Asana is the only app for which i can't get to target anything (except the standard macOS traffic light buttons). so weird. but other apps can, so it's on me. will need more time to investigate.

**Comment by godbout** [comment]
ok i've found the reason on Asana. i'm hiding UI elements that are 1 pixel high, because Brave/Chrome, rather than not generating or hiding those elements, spread a billion across a page and that slows down things unnecessarily. the issue here is that Asana does something similar with one UI element, in which it puts all the others. no idea why they do that, but then i filter out all the children. will need to find a way to make Asana work without slowing down Wooshy. may take a while.

**Comment by godbout** [comment]
support improved in a6: https://github.com/godbout/Wooshy.docs/releases/tag/1a.6

but still some stuff to do on the AX Engine to grab more stuff.

**Comment by godbout** [comment]
closing coz @dudunato is never gonna do its job!
