### ISSUE TITLE
Feature request: activate from kindaVim normal mode

### ISSUE THREAD

**Issue by haveanicedavid** [godbout/Wooshy.docs#66]
See title 😄 

I often enter kV normal mode in apps to do things like… parse through email inbox, and it would be great to be able to have an option for allowing wooshy to activate without having to first exit normal mode.

(PS - still loving both apps, and am becoming a bit of an evangelical about how awesome they are… seriously can’t thank you enough for building these)

**Comment by godbout** [comment]
> I often enter kV normal mode in apps to do things like… parse through email inbox, and it would be great to be able to have an option for allowing wooshy to activate without having to first exit normal mode.

in kV you have the `passthrough` options:

<img width="766" alt="Screenshot 2022-08-26 at 12 16 48" src="https://user-images.githubusercontent.com/121373/186821178-3b7ad48a-938a-45a1-b9bc-c0b6eb06a3fb.png">

if you combine this with the keyboard shortcut you use to start Wooshing, then it'll go through and kV will exit Normal Mode automatically.

if you mean _staying_ in Normal Mode, that's not possible. at least not without a major rewrite of kV. when you enter Normal Mode, kV needs to track of a lot of info in the current focused field. as soon as you leave that field, your kV "environment" is gone, and a new one will restart when you focus somewhere again, and enter Normal Mode (again). i don't even think a rewrite could work. i've explored at the beginning keeping kV status over the whole macOS rather than the focused field, but the lack of APIs makes this almost impossible IIRC.

in the case you want to start Wooshing with a keyboard shortcut that doesn't contain an allowed modifier, i'm pretty sure you could do something with Hammerspoon or another tool, and remap the shortcut.

> (PS - still loving both apps, and am becoming a bit of an evangelical about how awesome they are… seriously can’t thank you enough for building these)

🙏🏼️ glad they help and make you... have a nice day. (ha ha ha again.)
but please, try not to be too evangelical. i still need criticisms 😂️

**Comment by haveanicedavid** [comment]
Ahh, that makes sense - thanks for explaining! 

Would it be hard to add `left_ctrl` to the passthrough options of kV? Happy to make a feature in the other repo if necessary, but if it’s more than a simple change then I’ll just make alt work (I’m a web dev - very ignorant of macOS apis)

**Comment by godbout** [comment]
> Would it be hard to add `left_ctrl` to the passthrough options of kV?

there's a reason why `CTRL` is not part of the passthrough options unfortunately: this is a used key in Vim, like `CTRL-F/B/U/D`. `command` and `alt` are not used by Vim, which is why they are used.

what's your keyboard shortcut for Wooshy?

**Comment by haveanicedavid** [comment]
currently `ctrl + /` -  I have a fairly proprietary setup with both a karabiner config that rebinds capslock to escape if tapped / ctrl is held + an [ergodox](https://www.zsa.io/moonlander) with some toggles for ctrl (due to my other vim setup - ctrl + hjkl = basic movements) so it’s a convenient mod key for me, but honestly not a big deal. I’ll just change to `alt + /`. Muscle memory isn’t too set, fortunately, and this solves my original reason for making this FR (already changed the binding)

Thanks again!

**Comment by godbout** [comment]
> + an [ergodox](https://www.zsa.io/moonlander)

ah those guys contacted me last week regarding kV and Wooshy 😂️😂️😂️ are you the one who sent them? 😂️

hmm i think even with your setup there's something that could be done. like you could assign Wooshy to a shortcut having a `command` and/or an `alt`. then in Karabiner/Hammerspoon you remap your `ctrl + /` to that. i'm far from being an expert with those tools but that seems very possible to me.

**Comment by haveanicedavid** [comment]
> are you the one who sent them?

Honestly couldn’t tell you at this point. I have a tendency to be very loud with the folks who appreciate the same things I do about the tools I’ve discovered and want to see succeed (for selfish reasons - I’d be sad now if kV / wooshy go away) so at this point I’ve sorta lost track. 

> in Karabiner/Hammerspoon you remap your ctrl + / to that shortcut

Why hadn’t I thought of that! Actually shouldn’t be that hard with hammerspoon - will definitely try!

**Comment by godbout** [comment]
> Honestly couldn’t tell you at this point. I have a tendency to be very loud with the folks who appreciate the same things I do about the tools I’ve discovered and want to see succeed (for selfish reasons - I’d be sad now if kV / wooshy go away) so at this point I’ve sorta lost track 😂

😅️😂️

> (for selfish reasons - I’d be sad now if kV / wooshy go away)

benevolent selfishness is good. FWIW, kV and Wooshy will not disappear. same reason as your selfishness: i need them and build them for myself first. i'll need them for as long as i need a computer. not that i _love_ computers, but i **love** my freedom (migrating following the heat) and i **love** (need?) to build things. computers allow me to have both, quickly. so i don't see this going away. in case it does tho (never know), or if i die suddenly, processes are put into place so that kV and Wooshy go open source. the point of being closed currently is that when kV was open i had to deal with a lot of "support" even tho i warned i wouldn't do OSS support. waste of time and energy. now i can ignore the requests guilt-free. the points of being paid apps is not that i can buy a Ferrari, it's that i can buy myself the time to work on them without having to take shit jobs. (any other job is considered shit yes.)

feels like i've already said that before but with a Lamborghini no? 🤔️ well at least i'm mostly consistent.

> Why hadn’t I thought of that!

usually the excuses i use are 1) not had coffee yet 2) too many beers already.

**Comment by jannis-baum** [comment]
@haveanicedavid Since it looks like you already use Hammerspoon and Karabiner, maybe [this discussion](https://github.com/godbout/kindaVim.docs/discussions/117) will be interesting for you! It explains how you can remap a key *only* in kV Normal mode, so you could, for example, activate Wooshy with just `q` or some other unused key.

**Comment by haveanicedavid** [comment]
> i need them and build them for myself first
🙌 

> and i love (need?) to build things
SAME

> or if i die suddenly
Let’s hope not! But thank you for the contingencies 😂 

Zero shame in non-OSS / paid software IMO. You’re committing 100% of the labor toward a tool that’s provding others (me) value. Plenty of folks drive ferraris who have done far less - I hope you get one!

> 1) not had coffee yet 2) too many beers already.

hahaha last night it was definitely 2. Right now, it’s 1

**Comment by godbout** [comment]
> Let’s hope not! But thank you for the contingencies 😂

😅️ well it'd make no sense to keep charging or keeping stuff closed source right? 😀️ that being said, i'm not planning to die before the next 47 years at least.

> Zero shame in non-OSS / paid software IMO. You’re committing 100% of the labor toward a tool that’s provding others (me) value. Plenty of folks drive ferraris who have done far less - I hope you get one!

that's the way i see it yeah. and it's a free market. if people don't find the value it's fine. but what's always strange to me is rather than moving on, some keep arguing. strange coz if you just pay 3 something US you don't waste lots of time and energy arguing 😂️

> > 1. not had coffee yet 2) too many beers already.

turned 41 yesterday. whole day today was point 2. for me ☹️ i try to drink without counting no more than once a year. it's still one time too many. some stuff you never learn...

**Comment by godbout** [comment]
@haveanicedavid anything else i can/should do here? (closing issues time!) if yes please let me know.

**Comment by haveanicedavid** [comment]
@godbout Nope! Good to close

> what's always strange to me is rather than moving on, some keep arguing.

In my experience, those are often the same people who will spend $10 per day on a latte 😄 Don’t mind the haters — you’re doing good work (and $3/day is very reasonable)

One minor suggestion though (not that you asked) would be a short ‘full run’ trial mode before the request for license kicks in… like a week of being able to use in the mornings without the warning before it kicks in. I mention that just becuase I’ve suggested kV to some friends, and they intended to use just in the available times — but disabled in the mornings and forgot in the afternoon. A free trial period could get folks like that hooked on the greatness of kV (and train their muscle memory 👿 ), which would make justifying the license easier.

Honestly though, the pricing is really fair for the value it adds so I don’t think it’s a big deal either way, just thought it might help with pulling in paid customers, so seems worth mentioning

**Comment by godbout** [comment]
> One minor suggestion though (not that you asked) would be a short ‘full run’ trial mode before the request for license kicks in… like a week of being able to use in the mornings without the warning before it kicks in. I mention that just becuase I’ve suggested kV to some friends, and they intended to use just in the available times — but disabled in the mornings and forgot in the afternoon. A free trial period could get folks like that hooked on the greatness of kV (and train their muscle memory 👿 ), which would make justifying the license easier.

ah thanks for letting me know. you're not the first to tell me this so i really have to look at it. there's several reasons why i didn't do it at first 1) i have no interest dealing with licensing stuff ☹️ 2) i think/thought if people really need/want kV, they'll try it in the afternoon 3) if you give a full trial you need to set up a bunch of bullshit to prevent user to keep running it forever.

but again, i've had the same feedback from other people. so it's definitely something i need to look at more seriously. thanks for confirming!
