### ISSUE TITLE
not working on Terminal & iTerm2

### ISSUE THREAD

**Issue by roelvangils** [godbout/Wooshy.docs#72]
Haha 🙂 I think that's not needed at probably not possible… but hey, maybe some people would like to click on paths and URLs in a Terminal window.

**Comment by godbout** [comment]
the whole text within Terminals is just one UI Element/value. so we can't distinguish the different parts of the text.

![Screenshot 2022-09-11 at 00 09 45](https://user-images.githubusercontent.com/121373/189492010-89513c33-50af-4fd3-bf25-70e8800204d9.png)

**Comment by roelvangils** [comment]
Yes, that is what I expected. Don't worry :)

**Comment by godbout** [comment]
closing as nothing to do here.

**Comment by godbout** [comment]
> Shame, this would be really nice as a consolidated, system wide replacement for something like hop / easy motion.

yeah. i'm revisiting this from time to time, when people mention/request again. but i don't expect things to change. if you can find a competitor that is handling this better than Wooshy then let me know, that would mean i may be missing something. thanks!

**Comment by lougreenwood** [comment]
Not sure it's helpful, but I notice that both iTerm & apple Terminal app allow searching the terminal (`cmd-f`). So internally it seems it's possible, whether there's a public api which allows searching and interacting with the terminal content via Wooshy.

Did you consider reaching out to one/some of the terminal apps to see if it would be possible for some tighter integration? I also just did a quick search to see if there are any terminals which render using HTML which might work off the shelf, but seems there are none...

**Comment by godbout** [comment]
> Not sure it's helpful, but I notice that both iTerm & apple Terminal app allow searching the terminal (`cmd-f`). So internally it seems it's possible, whether there's a public api which allows searching and interacting with the terminal content via Wooshy.

tbh not sure what you're trying to achieve here. Terminal and iTerm actually use Text Areas for their shells, with AX info. so each shell (panel) is reachable by Wooshy. then it's also up to each app how they integrate the macOS Accessibility. for example, in the Terminal and iTerm, the whole shell is _one_ Text Area. the data is not split by paragraph, sentence, or word. so you can use Wooshy to target a word, and highlight the whole panels where the word is. but you can't pinpoint/highlight a specific word.

see the video below, the Text Area with the data are there, and Wooshy can reach them:


https://user-images.githubusercontent.com/121373/215237863-b44255cf-5214-4a5d-9fce-19fe27a4cd5b.mp4

> Did you consider reaching out to one/some of the terminal apps to see if it would be possible for some tighter integration?

again, not sure what "integration" you mean. on the one hand, Wooshy uses AX info. all the engines are based on dealing with the AX. there's no way to create a new engine per app lol, to get some sort of "integration". and also yeah i still don't get what you're trying to do. i guess what you may want to do is to reach a panel with Wooshy, and then use `cmd f` to search? it's hard to relate for me because i personally don't use Wooshy at all with iTerm. i move along panels and tabs with some Vim motions (hjkl), and i never "search" through the macOS finding thing. i use zsh functionalities.

**Comment by lougreenwood** [comment]
> tbh not sure what you're trying to achieve here.

Sorry, maybe I wasn't clear. What I'm talking about is being able to target specific items in the terminal. E.g selecting an item in an nvim Telescope menu or clicking on a window in tmux - like a universal hop /easy motion that works both in MacOS and CLI apps. But like you say, the apps only expose one big text area, so it's not possible to do that.

> use cmd f to search? 

The only reason I mentioned using search / cmd f was because I wanted to check if internally the terminals track the shell contents and the problem was the "presentation" of the shell as a text area. But I guess if it's just one big text macOS is just searching the contents of that.

So to be clear, I'm not trying to use search here 😉.

Anyways, like you said, it's not possible since the terminal apps just render it all as one big text area. I guess I'd need to find a terminal app which renders it's contents in a more fine-grained way, but I doubt that exists....

**Comment by godbout** [comment]
> Sorry, maybe I wasn't clear. What I'm talking about is being able to target specific items in the terminal. E.g selecting an item in an nvim Telescope menu or clicking on a window in tmux - like a universal hop /easy motion that works both in MacOS and CLI apps. But like you say, the apps only expose one big text area, so it's not possible to do that.

oh i see. my bad. i'm not using those tools so i couldn't really get it, but now i do.

> The only reason I mentioned using search / cmd f was because I wanted to check if internally the terminals track the shell contents and the problem was the "presentation" of the shell as a text area. But I guess if it's just one big text area then macOS is just searching the contents of that.
> 
> So to be clear, I'm not trying to use search here 😉.

got it.

> Anyways, like you said, it's not possible since the terminal apps just render it all as one big text area. I guess I'd need to find a terminal app which renders it's contents in a more fine-grained way, but I doubt that exists....

yeah. i mean i've personally used iTerm for ages. fits my needs. but i've tried several other terminals because of users requesting them to be supported by Wooshy. and for most of them it's even worse (GPU rendering, zero AX, etc.). so yeah i'm not sure what's the reason? i guess if it was easy and/or doable, someone would have made something that you can tweak through HTML/CSS/JS? actually maybe it makes zero sense. things should be tweaked through your shell configs? not absolutely sure. but that's the current state of affairs it seems yeah.
