### ISSUE TITLE
Suggestion: Cycle through targets with tab and arrow keys

### ISSUE THREAD

**Issue by blackketter** [godbout/Wooshy.docs#78]
When using the tab or arrow keys to navigate between targets it would be great if when reaching the end of the selectable items to move on to the first one with the next tab or arrow, looping around in a cycle.

**Comment by godbout** [comment]
yeah, currently it stops. any "use case"?

do you know that you can go directly to the first, last, or even in the middle with keyboard shortcuts? https://github.com/godbout/Wooshy.docs#navigate

just wondering in which case this would be needed/useful. thanks.

**Comment by blackketter** [comment]
I find myself using tab to move around quickly and sometimes overshoot.  My muscle memory just keeps hitting tab expecting to cycle around.  This is pretty standard in the Mac UI: 


https://user-images.githubusercontent.com/131679/190921558-f0aaba83-304d-436a-8399-66a59ae9e684.mov

**Comment by godbout** [comment]
> I find myself using tab to move around quickly and sometimes overshoot. My muscle memory just keeps hitting tab expecting to cycle around. 

ok, took me a while to understand your point 😂️
from what you're saying it would actually be better if Wooshy doesn't allow you to overshoot (current behavior), and you could go back with `shift tab`. so i assume that you're talking in the cases where you have very few Targets, and you'd rather keep pressing `tab` rather than `shift tab` and going back, right? if it's not this case then i don't get it because actually blocking the overshoot would allow you to quickly go back to the Target you want.

**Comment by blackketter** [comment]
Yes, this is generally more useful for situations when there are relatively few targets.  Shift-Tab should continue to work, of course.  If you overshoot and loop around then shift-tab will take you back.

For me, it's just a little standard Mac behavior that is missing.

**Comment by godbout** [comment]
alright. thanks. i personally like the fact that it stops at the first and last. but i'll probably add an option to cycle through.

**Comment by godbout** [comment]
available as an option in a24: https://github.com/godbout/Wooshy.docs/releases/tag/1.a24

**Comment by godbout** [comment]
@blackketter any feedback? thanks.

**Comment by blackketter** [comment]
Works great!
