### ISSUE TITLE
not working on Visual Studio Code

### ISSUE THREAD

**Issue by Soft-Bred** [godbout/Wooshy.docs#98]

**Comment by godbout** [comment]
Visual Studio Code is explicitly supported by Wooshy. so what is not working? the whole app? or just some parts? if only some parts that would be because those parts are not exposed to the macOS AX. also, you're using the vanilla version, or some special one like dev version etc? coz like for Figma, if it's a special version with its own bundle ID, then i'll have to explicitly add support for it, yes. lemme know.

**Comment by Soft-Bred** [comment]
Hmm, thats odd:

https://user-images.githubusercontent.com/60551230/208600226-fb6eb8d5-aa0c-4629-a38f-7dea719cddfa.mp4

**Comment by godbout** [comment]
not on a computer now, but can you make sure that it's the vanilla version of Studio Code by getting me the bundle ID: https://www.hexnode.com/mobile-device-management/help/how-to-find-the-bundle-id-of-an-application-on-mac/

thanks.

**Comment by godbout** [comment]
@Soft-Bred i'm seeing the issue sometimes. can you try hiding VSCode, and showing it again. then activate The Input again. should work. if it works then i may need to do something. most probably VSCode takes too long to spawn up their AX framework.

**Comment by godbout** [comment]
can you get me the bundle ID then to be sure first, thanks. see two comments above.

**Comment by godbout** [comment]
technically Wooshy (and kV and Scrolla) holds an App Catalog to know on which app it needs to do what in order to get the macOS Accessibility... accessible. native apps work out of the box but the Electron turds are a nightmare. and there's some VIP treatments for Google stuff of course. the App Catalog could be avoided by blasting all the apps as soon as they're into focus, but that would be a waste of resources. furthermore, for kindaVim that is much more complex, i need to test every app manually, hence the App Catalog.

for Visual Studio Code, Wooshy needs to blast some attributes for app to expose its UI Elements. you can see this in action below:

https://user-images.githubusercontent.com/121373/208812501-2f2bfafa-77b5-466d-9327-719865fe4645.mp4

there's a balance between shooting the app indefinitely, and stopping when the AX is activated. Wooshy will blast an app 12 times max. if the app doesn't advertise that it is now accessible, it will stop after 12 times (again, for resources reasons). but it the app advertises that it is now accessible, Wooshy stops blasting.

as you can see in the video, Wooshy blasts only a couple of times. this is because Code is saying "good, i've exposed my UI Elements now." but... it's not true. it still hasn't exposed them. then you target with Wooshy, Wooshy sees nothing.

now when an app comes back into focus, Wooshy checks and may blast another time. this is why—at least in my case—the elements are exposed once i **hide and unhide** the app.

that's for the explanation. Code was working well a few months ago when i added support. that's the issue with dealing with something as picky and complex as the AX framework, things may change. apps are constantly updating, and breaking their own AX support, and this is not something i can control. just keep checking, being aware, and patching.

i will probably have to do something regarding this on my side. but something is still very strange here, which is: why you still can't use Wooshy even after hiding and unhiding Code.

so, conclusion, yeah, the next step is for you to get me the bundle ID just to make sure we're on the same page.

**Comment by Soft-Bred** [comment]
Bundle id should be "com.microsoft.VSCode"

**Comment by godbout** [comment]
hmm. strange then. Wooshy will blast "com.microsoft.VSCode" with the proper AX attribute and it should definitely works when you unhide the app.

**Comment by godbout** [comment]
ok i'm adding some other special AX attribute and tweaking stuff so that it should work in v3, without having to hide/unhide. hopefully it'll work for you too. thoughts and prayers may be required.

**Comment by godbout** [comment]
made changes in v3: https://github.com/godbout/Wooshy.docs/releases/tag/3

please check again, and if it works we can close! thanks.
